version: '3.3'

services:
  db:
    image: postgres:15
    container_name: birdsong_db
    restart: always
    environment:
      POSTGRES_DB: birdsong_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: birdsong_api
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=birdsong_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_DIALECT=postgres
      - NODE_ENV=production
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ../json_parts:/app/json_parts
      # 设置挂载卷的用户ID，确保容器内用户可以访问
    user: "1001:1001"

volumes:
  postgres_data: